spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: yourDatabaseName
    redis:
      host: localhost
      port: 6379
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://localhost:6379"
